# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    ## create YML
    - name : Create Application YML File
      run : |
        echo "${{secrets.APPLICATION_YML}}" | base64 --decode > src/main/resources/application.yml
        find src

    ## gradle build
    - name: Build with Gradle
      run: ./gradlew build

  docker_build_and_push:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    ## image Build and Push
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_REPO }}:latest
        
  deploy_ec2:
    needs: docker_build_and_push
    runs-on: ubuntu-latest

    steps:
    ## Deploy 
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
              sudo docker rm -f $(sudo docker ps -qa) # Remove all running containers
              sudo docker pull ${{ secrets.DOCKER_REPO }}:latest 
              sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_REPO }}:latest
